### ISSUE TITLE
JBoss Data Virtualization quickstart has no data

### ISSUE THREAD

**Issue by mechevarria** [jboss-openshift/openshift-quickstarts#61]
The current quickstart is against an H2 database that contains no data.  It would be helpful for demos if that source had a few rows of data or the excel datasource was prepared so that a configuration change can reference it and return some example data

**Comment by rcernich** [comment]
The db is there, but there were some changes made recently to the way s2i works in that it no longer copies the entire source tree into /home/jboss/source/.  I suspect this is why you're seeing an empty db.  We are working to address the issue.

The db file is located here: https://github.com/jboss-openshift/openshift-quickstarts/tree/master/datavirt/dynamicvdb-datafederation/app/data/databases/h2

In the meantime, you can use one of the other flavors of db, e.g. postgresql, instructions for which can be found here: https://github.com/jboss-openshift/openshift-quickstarts/tree/master/datavirt/dynamicvdb-datafederation/postgresql
